// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

/// Flutter icons GitleIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GitleIcons
///      fonts:
///       - asset: fonts/GitleIcons.ttf
///
///
/// * Entypo, Copyright (C) 2012 by Daniel Bruce
///         Author:    Daniel Bruce
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.entypo.com
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
class GitleIcons {
  GitleIcons._();

  static const _kFontFam = 'GitleIcons';

  static const IconData flow_branch = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData tag = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData inbox = IconData(0xf01c, fontFamily: _kFontFam);
}
